# Generated by Django 4.1.7 on 2023-02-15 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Идентификатор')),
                ('date', models.DateField(verbose_name='Дата')),
                ('content', models.TextField(max_length=1000, verbose_name='Контент')),
                ('url', models.CharField(max_length=500, verbose_name='Вложенные url')),
                ('tag', models.CharField(max_length=100, verbose_name='Тэг')),
            ],
            options={
                'verbose_name': 'Пост',
                'verbose_name_plural': 'Посты',
                'ordering': ['date', 'tag'],
            },
        ),
    ]
