# Generated by Django 4.1.7 on 2023-02-15 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_posts_postsmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postsmodel',
            name='content',
            field=models.TextField(max_length=3000, verbose_name='Контент'),
        ),
        migrations.AlterField(
            model_name='postsmodel',
            name='url',
            field=models.CharField(max_length=100, verbose_name='Вложенные url'),
        ),
    ]
