# Generated by Django 4.1.7 on 2023-02-15 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_postsmodel_content_alter_postsmodel_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postsmodel',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
