# Generated by Django 4.1.7 on 2023-02-15 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_postsmodel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postsmodel',
            name='date',
            field=models.DateTimeField(verbose_name='Дата'),
        ),
    ]
