# Generated by Django 4.1.7 on 2023-02-15 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Posts',
            new_name='PostsModel',
        ),
    ]
