# Generated by Django 4.1.7 on 2023-02-16 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_postsmodel_url_urlsmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlsmodel',
            name='url',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='app.postsmodel', verbose_name='Вложенные url'),
        ),
    ]
