# Generated by Django 4.1.7 on 2023-02-16 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_urlsmodel_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='urlsmodel',
            old_name='url',
            new_name='post',
        ),
    ]
