# Generated by Django 4.1.7 on 2023-02-16 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_rename_url_urlsmodel_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='urlsmodel',
            old_name='post',
            new_name='url',
        ),
    ]
