# Generated by Django 4.1.7 on 2023-02-16 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_urls_rename_postsmodel_post_delete_urlsmodel_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='PostsModel',
        ),
        migrations.RenameModel(
            old_name='Urls',
            new_name='UrlsModel',
        ),
    ]
